#!/usr/bin/env python

import argparse
import os

command = 'ansible-playbook {0} -i hosts --extra-vars "hosts={2} env={1} app={3}"'

def deploy(args):
    if not args.playbook:
        print "mastful: error: argument playbook is required"
        exit(1)
    return command.format("whaler.yml", args.e, args.hosts, args.playbook)

def install(args):
    return command.format("docker.yml", args.e, args.hosts, "")

parser = argparse.ArgumentParser(description="App to manage docker containers")
parser.add_argument("action", help="what to do")
parser.add_argument("playbook", nargs="?",  help="which playbook to run")
parser.add_argument("-e", help="environment for app", required=False, default="dev")
parser.add_argument("-hosts", help="host to deploy app on", required=True)
parser.add_argument("-d", help="debug", required=False, action="store_true", default=False)
parser.add_argument("-a", help="debug", required=False, action="store_true", default=False)

args = parser.parse_args()
if args.action not in ["install", "deploy"]:
    print "Sepcify either 'install' or 'deploy'"
    exit(0)

command = locals()[args.action](args)
if args.d:
    command = command + " -vvvv"
os.system(command)

if args.a:
    os.system("docker attach " + args.playbook)
